FROM jthet/container-base:latest

LABEL maintainer="Jackson Thetford"

COPY requirements.txt .

RUN pip install git+https://github.com/specufex/specufex.git \
    && pip install -r requirements.txt \
    && mamba install scikit-learn \
    && rm requirements.txt \
    && docker-clean

RUN git clone https://github.com/specufex/specufex.git

USER ${NB_UID}
WORKDIR "${HOME}"

EXPOSE 8888

COPY extras/startup-tacc.sh /usr/bin/
RUN chmod +x /usr/bin/startup-tacc.sh

ENTRYPOINT ["tini", "-s", "-g", "--", "/entry.sh", "/usr/bin/startup-tacc.sh"]
